
name: License Report

on:
  pull_request:
    branches:
      - $default-branch
jobs:
  generate_report:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    name: "Generate Report of Package Usage"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: ${{ github.head_ref }}
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run co:login
      - run: npm install
      - run: npm install -g license-checker
      - run: mkdir -p package-reports
      - run: license-checker --summary > package-reports/license-summary.txt
      - run: license-checker --onlyunknown > package-reports/license-unknown.txt
      - run: license-checker > package-reports/licenses.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Package License Report
          file_pattern: package-reports/*
